export interface SeedSumberDana {
  nama_cabang: string;
  skg: number;
  nominal: number;
}

export const seedDataSumberDana: SeedSumberDana[] = [
  { nama_cabang: "Kanjeng Guru KH Imroni Abdillah", skg: 0, nominal: 0 },
  { nama_cabang: "BANDUNG", skg: 17, nominal: 0 },
  { nama_cabang: "BATANG", skg: 18, nominal: 0 },
  { nama_cabang: "BOJONEGORO 1 - KAPAS", skg: 2, nominal: 0 },
  { nama_cabang: "BOJONEGORO 2 - SEKAR", skg: 24, nominal: 0 },
  { nama_cabang: "CIREBON", skg: 15, nominal: 0 },
  { nama_cabang: "DEMAK 1 - WONOKETINGAL", skg: 40, nominal: 0 },
  { nama_cabang: "DEMAK 2 - DEMPET", skg: 40, nominal: 0 },
  { nama_cabang: "DEMAK 3 (MRANGGEN)", skg: 37, nominal: 0 },
  { nama_cabang: "GARUT", skg: 4, nominal: 0 },
  { nama_cabang: "GROBOGAN 1 - PURWODADI", skg: 57, nominal: 0 },
  { nama_cabang: "GROBOGAN 2 - GODONG", skg: 16, nominal: 0 },
  { nama_cabang: "JAKARTA SELATAN", skg: 25, nominal: 0 },
  { nama_cabang: "JAMBI", skg: 80, nominal: 0 },
  { nama_cabang: "JEPARA", skg: 357, nominal: 0 },
  { nama_cabang: "KENDAL 1 - CEPIRING", skg: 23, nominal: 0 },
  { nama_cabang: "KENDAL 2 - BOJA", skg: 26, nominal: 0 },
  { nama_cabang: "KENDAL BOTOMULYO", skg: 5, nominal: 0 },
  { nama_cabang: "KLATEN", skg: 10, nominal: 0 },
  { nama_cabang: "PALEMBANG - KOTA", skg: 12, nominal: 0 },
  { nama_cabang: "PALEMBANG - SEKAYU", skg: 4, nominal: 0 },
  { nama_cabang: "PEMALANG 1 - BELIK", skg: 30, nominal: 0 },
  { nama_cabang: "PEMALANG 2 - ULUJAMI", skg: 11, nominal: 0 },
  { nama_cabang: "Pengurus Pusat", skg: 0, nominal: 0 },
  { nama_cabang: "PONOROGO", skg: 109, nominal: 0 },
  { nama_cabang: "PURWOREJO", skg: 30, nominal: 0 },
  { nama_cabang: "RIAU", skg: 8, nominal: 0 },
  { nama_cabang: "SEMARANG - CANDILAMA", skg: 27, nominal: 0 },
  { nama_cabang: "SEMARANG - GENUK", skg: 7, nominal: 0 },
  { nama_cabang: "SEMARANG KALICARI", skg: 14, nominal: 0 },
  { nama_cabang: "SEMARANG - KROBOKAN", skg: 17, nominal: 0 },
  { nama_cabang: "SEMARANG - MIJEN", skg: 11, nominal: 0 },
  { nama_cabang: "SEMARANG - NGALIYAN", skg: 12, nominal: 0 },
  { nama_cabang: "SEMARANG - PEDURUNGAN", skg: 25, nominal: 0 },
  { nama_cabang: "SEMARANG - PUSAT", skg: 251, nominal: 0 },
  { nama_cabang: "SOLO", skg: 55, nominal: 0 },
  { nama_cabang: "TANGERANG", skg: 32, nominal: 0 },
  { nama_cabang: "TEGAL 1 - KOTA", skg: 6, nominal: 0 },
  { nama_cabang: "TEGAL 2 - SLAWI", skg: 0, nominal: 0 },
  { nama_cabang: "TEGAL BARU", skg: 6, nominal: 0 },
  { nama_cabang: "TEMANGGUNG", skg: 45, nominal: 0 },
  { nama_cabang: "UNGARAN 1 - GOGIK", skg: 153, nominal: 0 },
  { nama_cabang: "UNGARAN 2 - JATIRUNGGO", skg: 139, nominal: 0 },
  { nama_cabang: "UNGARAN 3 - BABADAN", skg: 11, nominal: 0 },
  { nama_cabang: "YOGYAKARTA", skg: 35, nominal: 0 },
  { nama_cabang: "Wali Santri PPTQCT", skg: 0, nominal: 0 },
  { nama_cabang: "Belum Konfirmasi", skg: 0, nominal: 0 },
];
